### ISSUE TITLE
Get error when I run this package sample code. Using Python 3.5.2 on Ubuntu

### ISSUE THREAD

**Issue by pwalimbe** [blockstack/keychain-manager-py#2]
Traceback (most recent call last):
  File "/home/prasanna/Src/verify/be/model/apikey.py", line 76, in <module>
    private_keychain = PrivateKeychain("xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi")
  File "/home/prasanna/Envs/block/lib/python3.5/site-packages/keychain/private_keychain.py", line 17, in __init__
    elif isinstance(private_keychain, (str, unicode)):
NameError: name 'unicode' is not defined

**Comment by larrysalibra** [comment]
@pwalimbe try using python 2.7

**Comment by pwalimbe** [comment]
It did solve it. However since our firm has made py3 as the default stack, I was wondering if there is py3 version of this?

**Comment by pwalimbe** [comment]
Just wanted a comment on your plans for py3 migration?
